name: Backend Continuous Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: starter/backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'
          cache: 'pipenv'
          cache-dependency-path: starter/backend/Pipfile.lock
          
      - name: Install Dependencies & Linter
        run: |
          pip install pipenv flake8
          pipenv install --dev
          
      - name: Execute Linter
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'
          cache: 'pipenv'
          cache-dependency-path: starter/backend/Pipfile.lock
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run test

  build-and-deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compile and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Sync Kubeconfig
        run: aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Rollout to EKS Cluster
        working-directory: starter/backend/k8s
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kustomize edit set image backend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kustomize build | kubectl apply -f -