name: Frontend Continuous Integration

on:
  push:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'

defaults:
  run:
    working-directory: starter/frontend

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter / Build Check
        run: npm run build